export const SiteContent = {
    title: "Docs Diver",
    description: "Upload technical documents, search them semantically, and get citation-based AI answers.",
    dashboard: "Dashboard",
    workspaces: "Workspaces",
    workspacesDescription: "Organize documents, ask questions, and generate grounded answers.",
    newWorkspace: "New workspace",
    documents: "Documents",
    updated: "Updated",
    askQuestions: "Ask questions across indexed technical documents.",
    uploadPDF: "Upload PDF",
    chat: "Chat",
    chats: "Chats",
    firstQuestion: "Upload a document to enable chat",
    welcomeMessage: "Nice, your first document is indexed. Ask me anything about it and I will answer with source-backed citations.",
    questionPlaceholder: "Ask a question about your documents...",
    promptDescription: "Once documents are indexed, answers will include citations from your sources.",
    ask: "Ask",
    noDocumentsTitle: "No documents yet",
    noDocumentsDescription: "Upload PDFs to build this workspace.",
    create: "Create",
    chatError: "Failed to send message. Please try again.",
    chatErrorTimeout: "Request timed out. Please try again.",
    namespace: "New workspace name...",
    close: "Close",
    noWorkspacesTitle: "No workspaces yet",
    noWorkspacesDescription: "Create a workspace to start uploading documents.",
    workspaceNameRequired: "Workspace name is required",
    workspaceNameExists: "A workspace with this name already exists",
    workspaceCreationError: "Unable to create workspace right now. Please try again.",
    noUserIdError: "User id is required to load workspaces.",
    getWorkspacesError: "Unable to load workspaces right now. Please try again.",
    noWorkspaceIdError: "Workspace id is required.",
    noDocumentIdError: "Document id is required.",
    workspaceNotFoundError: "Workspace not found.",
    status: "Status",
    documentUploadError: "Unable to upload document right now. Please try again.",
    noPDFError: "PDF file is required",
    wrongFileTypeError: "Only PDF files are supported",
    uploadPDFDescription: "Upload a PDF to index it in this workspace and start asking grounded questions.",
    uploading: "Uploading...",
    workspaceSettings: "Workspace settings",
    workspaceSettingsDescription: "Rename this workspace or remove it permanently.",
    renameWorkspace: "Rename workspace",
    workspaceRenameError: "Unable to rename workspace right now. Please try again.",
    textExtractionError: "No text could be extracted from this PDF",
    documentNotFoundError: "Document not found.",
    documentDeleteError: "Unable to delete document right now. Please try again.",
    deleteDocument: "Delete document",
    deleteWorkspace: "Delete workspace",
    cancel: "Cancel",
    confirmDeleteDocumentTitle: "Delete document?",
    confirmDeleteDocumentDescription: "This action will permanently remove:",
    confirmDeleteWorkspaceTitle: "Delete workspace?",
    confirmDeleteWorkspaceDescription: "This action will permanently delete this workspace and all its documents.",
    chunks: "chunks",
    provideQuestion: "Please provide a question.",
    noInfoRetrieved: "I could not find relevant information in the uploaded documents.",
    noResponseFromModel: "The model returned an empty response. Please try again.",
    questionProcessingError: "An error occurred while processing your question. Please try again.",
    getMessagesError: "Unable to load messages right now. Please try again.",
    messagesLoadWarning: "Could not load previous messages. You can still continue chatting.",
    thinking: "Thinking...",
    aiUsage: "AI usage",
    aiUsageDescription: "Inspect the retrieval and model usage details for the last question.",
    sources: "Sources",
    source: "Source",
    chunk: "Chunk",
    similarity: "similarity",
    invalidWorkspaceIdError: "Invalid or missing workspaceId",
    invalidMessagesArrayError: "Invalid or empty messages array",
    invalidMessageContentError: "Invalid or empty message content",
    workspaceUnauthorizedError: "Workspace not found or unauthorized",
    saveMessageError: "Failed to save message",
    internalServerError: "Internal server error",
    getChatsError: "Unable to load chats right now. Please try again.",
    chatNotFoundError: "Chat not found.",
    chatCreationError: "Unable to create chat right now. Please try again.",
    noAIRequestsYet: "No AI requests yet.",
    lastAIRequest: "Last AI request",
    modelLabel: "Model:",
    inputTokensLabel: "Input tokens:",
    outputTokensLabel: "Output tokens:",
    latencyLabel: "Latency:",
    avgSimilarityLabel: "Avg similarity:",
    notAvailable: "N/A",
    usedChunks: "Used chunks",
    noUsedChunks: "No used chunks available.",
    retrievedChunks: "Retrieved chunks",
    noRetrievedChunks: "No retrieval data available.",
    question: "Question",
    answer: "Answer",
    evalTitle: "Retrieval Evaluation",
    evalDescription: "Inspect retrieved chunks and whether the model cited them.",
    workspaceDeleteError: "Unable to delete workspace right now. Please try again.",
    loadingPdf: "Loading PDF...",
    selectedChunkExcerpt: "Selected chunk excerpt",

};