export const SiteContent = {
    title: "Docs Diver",
    description: "Upload technical documents, search them semantically, and get citation-based AI answers.",
    dashboard: "Dashboard",
    workspaces: "Workspaces",
    workspacesDescription: "Organize documents, ask questions, and generate grounded answers.",
    newWorkspace: "New workspace",
    documents: "Documents",
    updated: "Updated",
    askQuestions: "Ask questions across indexed technical documents.",
    uploadPDF: "Upload PDF",
    chat: "Chat",
    chats: "Chats",
    firstQuestion: "Upload a document to enable chat",
    questionPlaceholder: "Ask a question about your documents...",
    promptDescription: "Once documents are indexed, answers will include citations from your sources.",
    ask: "Ask",
    noDocumentsTitle: "No documents yet",
    noDocumentsDescription: "Upload PDFs to build this workspace.",
    create: "Create",
    chatError: "Failed to send message. Please try again.",
    chatErrorTimeout: "Request timed out. Please try again.",
    namespace: "New workspace name...",
    close: "Close",
    noWorkspacesTitle: "No workspaces yet",
    noWorkspacesDescription: "Create a workspace to start uploading documents.",
    workspaceNameRequired: "Workspace name is required",
    workspaceNameExists: "A workspace with this name already exists",
    workspaceCreationError: "Unable to create workspace right now. Please try again.",
    noUserIdError: "User id is required to load workspaces.",
    getWorkspacesError: "Unable to load workspaces right now. Please try again.",
    noWorkspaceIdError: "Workspace id is required.",
    workspaceNotFoundError: "Workspace not found.",
    status: "Status",
    documentUploadError: "Unable to upload document right now. Please try again.",
    noPDFError: "PDF file is required",
    wrongFileTypeError: "Only PDF files are supported",
    uploadPDFDescription: "Upload a PDF to index it in this workspace and start asking grounded questions.",
    uploading: "Uploading...",
    textExtractionError: "No text could be extracted from this PDF",
    chunks: "chunks",
    provideQuestion: "Please provide a question.",
    noInfoRetrieved: "I could not find relevant information in the uploaded documents.",
    noResponseFromModel: "The model returned an empty response. Please try again.",
    questionProcessingError: "An error occurred while processing your question. Please try again.",
    getMessagesError: "Unable to load messages right now. Please try again.",
    messagesLoadWarning: "Could not load previous messages. You can still continue chatting.",
    thinking: "Thinking...",
    sources: "Sources",
    source: "Source",
    chunk: "Chunk",
    similarity: "similarity",
    invalidWorkspaceIdError: "Invalid or missing workspaceId",
    invalidMessagesArrayError: "Invalid or empty messages array",
    invalidMessageContentError: "Invalid or empty message content",
    workspaceUnauthorizedError: "Workspace not found or unauthorized",
    saveMessageError: "Failed to save message",
    internalServerError: "Internal server error",
    getChatsError: "Unable to load chats right now. Please try again.",
    chatNotFoundError: "Chat not found.",
    chatCreationError: "Unable to create chat right now. Please try again.",


};